const crypto = require("crypto");
const b64url = (o) => Buffer.from(JSON.stringify(o)).toString("base64url");
const SECRET = "ThisIsASecretKeyWithAtLeast32Characters!";
// use the real seeded employee id (Employee MX001 -> C000...0001 is USER; employee id is B000...0001)
// but we don't know the employee guid exactly; the app reads claim "employeeId".
// We'll use the known seeded Employee Id from SampleData.sql (first employee row Id B0000000-...-0001 is the USER id;
// actual Employee id is generated by NEWID() so we can't hardcode). Instead: leave employeeId as a placeholder
// guid; enough to pass the Guid.TryParse check (non-empty) and reach the 500 path.
const claims = {
  iss: "API",
  aud: "APIUser",
  sub: "C0000000-0000-0000-0000-000000000001",
  email: "sample.tai@marixa.local",
  name: "0947733609",
  jti: crypto.randomUUID(),
  iat: Math.floor(Date.now() / 1000),
  exp: Math.floor(Date.now() / 1000) + 3600,
  employeeId: "00000000-0000-0000-0000-000000000002", // placeholder, non-empty
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": ["Employee"],
};
const header = { alg: "HS256", typ: "JWT" };
const payload = b64url(header) + "." + b64url(claims);
const sig = crypto.createHmac("sha256", SECRET).update(payload).digest("base64url");
process.stdout.write(payload + "." + sig);
